#!/bin/bash

rsync -vart --checksum --stats --delete --progress "build/" -e ssh "rainwolf@development.pente.org:~/tomcat8/gameServer/mmai"
ssh rainwolf@development.pente.org chown -R rainwolf:tomcat8 tomcat8/
#ssh -t rainwolf@development.pente.org sudo ./restartTomcat.sh
